improve pipeline
add a build process for test, modify the release workflow to create changeset on stage branch. add workflow to sync stage and develop branches.

diff --git a/.github/workflows/enforce-pull-request-rules.yml b/.github/workflows/enforce-pull-request-rules.yml
--- a/.github/workflows/enforce-pull-request-rules.yml
+++ b/.github/workflows/enforce-pull-request-rules.yml
@@ -8,7 +8,12 @@ jobs:
     runs-on: ubuntu-20.04
     steps:
       - name: Check Pull Requests Against `main`
-        if: ${{ github.base_ref == 'main' && !contains(fromJson('["develop", "changeset-release/main"]'), github.head_ref) }}
+        if: ${{ github.base_ref == 'main' && !contains(fromJson('["stage"]'), github.head_ref) }}
         run: |
-          echo "Error: You can only merge to `main` from `develop`."
+          echo "Error: You can only merge to `main` from `stage`."
+          exit 1
+      - name: Check Pull Requests Against `stage`
+        if: ${{ github.base_ref == 'stage' && !contains(fromJson('["develop","fix/*"]'), github.head_ref) }}
+        run: |
+          echo "Error: You can only merge to `stage` from `develop or a fix branch`."
           exit 1
